name: Execution Build

on:
    push:
        branches: [ "main" ]
        paths:
            - 'execution/**'
            - '.github/workflows/execution-build.yml'

jobs:
    installDeps:
        name: 'Install Dependencies'
        uses: ./.github/workflows/setup-homebrew.yml
        with:
            packages: 'hatch python@3.11 isort black flake8 mypy'
            update-homebrew: true
    codeCheckout:
        name: 'Checkout Code'
        needs: installDeps
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
    codeBuild:
        name: 'Build Code with Hatch'
        needs: codeCheckout
        runs-on: ubuntu-latest
        steps:
            - name: Build the project
              run: |
                hatch pre-build && hatch build
    lintingChecks:
        name: 'Run Linting Checks'
        needs: codeBuild
        runs-on: ubuntu-latest
        steps:
            - name: Run isort
              run: |
                echo "Running isort..."
                isort ./execution --check-only --diff

            - name: Run black
              run: |
                echo "Running black..."
                black ./execution --check --diff

            - name: Run flake8
              run: |
                echo "Running flake8..."
                flake8 ./execution 

    mypyChecks:
        name: 'Run MyPy Checks'
        needs: codeBuild
        runs-on: ubuntu-latest
        steps:
            - name: Run mypy
              run: |
                echo "Running mypy..."
                mypy ./execution
    
    unitTests:
        name: 'Run Unit Tests'
        needs: codeBuild
        runs-on: ubuntu-latest
        steps:
            - name: Run unit tests
              run: |
                echo "Running unit tests..."
                hatch run test
              