name: Integration Build

on:
  push:
    branches: ["*"]
    paths:
      - 'integration_tests/**'
      - '.github/workflows/integration-build.yml'

jobs:
  codeBuild:
    name: 'Build Code with Hatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Build the project
        run: |
          hatch run pre-build && hatch build

  lintingChecks:
    name: 'Run Linting Checks'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Build the project
        run: |
          hatch run pre-build && hatch build
      - name: Run isort
        run: |
          echo "Running isort..."
          isort ./integration_tests --check-only --diff
      - name: Run black
        run: |
          echo "Running black..."
          black ./integration_tests --check --diff
      - name: Run flake8
        run: |
          echo "Running flake8..."
          flake8 ./integration_tests

  mypyChecks:
    name: 'Run MyPy Checks'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Build the project
        run: |
          hatch run pre-build && hatch build
      - name: Run mypy
        run: |
          echo "Running mypy..."
          mypy ./integration_tests

  unitTests:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Build the project
        run: |
          hatch run pre-build && hatch build
      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          hatch run test
