name: Setup Homebrew

on:
  workflow_call:
    inputs:
      packages:
        description: Space-separated list of packages to install via Homebrew
        required: false
        type: string
        default: ""
      update-homebrew:
        description: Whether to update Homebrew before installing packages
        required: false
        type: boolean
        default: true

jobs:
  setup-homebrew:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if Homebrew is already installed
        id: check-brew
        run: |
          if command -v brew &> /dev/null; then
            echo "installed=true" >> $GITHUB_OUTPUT
            echo "Homebrew is already installed"
          else
            echo "installed=false" >> $GITHUB_OUTPUT
            echo "Homebrew is not installed"
          fi

      - name: Install Homebrew
        if: steps.check-brew.outputs.installed == 'false'
        run: |
          echo "Installing Homebrew..."
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          
          # Add Homebrew to PATH for current session
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $GITHUB_ENV
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Setup Homebrew environment
        run: |
          # Ensure Homebrew is in PATH
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
          
          # Set environment variables
          echo "HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew" >> $GITHUB_ENV
          echo "HOMEBREW_CELLAR=/home/linuxbrew/.linuxbrew/Cellar" >> $GITHUB_ENV
          echo "HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew" >> $GITHUB_ENV

      - name: Verify Homebrew installation
        run: |
          which brew
          brew --version

      - name: Update Homebrew
        if: inputs.update-homebrew == true
        run: |
          echo "Updating Homebrew..."
          brew update

      - name: Install packages
        if: inputs.packages != ''
        run: |
          echo "Installing packages: ${{ inputs.packages }}"
          brew install ${{ inputs.packages }}

      - name: Verify package installations
        if: inputs.packages != ''
        run: |
          echo "Verifying installed packages..."
          for package in ${{ inputs.packages }}; do
            echo "Checking $package..."
            if brew list | grep -q "^$package$"; then
              echo "✅ $package is installed"
              # Try to run the package if it's a command
              if command -v "$package" &> /dev/null; then
                echo "🔍 $package version: $($package --version 2>/dev/null || echo 'Version check not supported')"
              fi
            else
              echo "❌ $package installation failed"
              exit 1
            fi
          done